
export enum SurveyActionType {
    UPDATE_SURVEY_TITLE = 'UPDATE_SURVEY_TITLE',
    UPDATE_BLOCK_TITLE = 'UPDATE_BLOCK_TITLE',
    UPDATE_BLOCK = 'UPDATE_BLOCK',
    UPDATE_QUESTION = 'UPDATE_QUESTION',
    ADD_QUESTION = 'ADD_QUESTION',
    ADD_QUESTION_FROM_AI = 'ADD_QUESTION_FROM_AI',
    DELETE_QUESTION = 'DELETE_QUESTION',
    COPY_QUESTION = 'COPY_QUESTION',
    REORDER_QUESTION = 'REORDER_QUESTION',
    ADD_CHOICE = 'ADD_CHOICE',
    DELETE_CHOICE = 'DELETE_CHOICE',
    ADD_PAGE_BREAK_AFTER_QUESTION = 'ADD_PAGE_BREAK_AFTER_QUESTION',
    ADD_BLOCK = 'ADD_BLOCK',
    DELETE_BLOCK = 'DELETE_BLOCK',
    COPY_BLOCK = 'COPY_BLOCK',
    REORDER_BLOCK = 'REORDER_BLOCK',
    MOVE_BLOCK_UP = 'MOVE_BLOCK_UP',
    MOVE_BLOCK_DOWN = 'MOVE_BLOCK_DOWN',
    ADD_BLOCK_FROM_TOOLBOX = 'ADD_BLOCK_FROM_TOOLBOX',
    BULK_DELETE_QUESTIONS = 'BULK_DELETE_QUESTIONS',
    BULK_DUPLICATE_QUESTIONS = 'BULK_DUPLICATE_QUESTIONS',
    BULK_UPDATE_QUESTIONS = 'BULK_UPDATE_QUESTIONS',
    BULK_MOVE_TO_NEW_BLOCK = 'BULK_MOVE_TO_NEW_BLOCK',
    MOVE_QUESTION_TO_NEW_BLOCK = 'MOVE_QUESTION_TO_NEW_BLOCK',
    MOVE_QUESTION_TO_EXISTING_BLOCK = 'MOVE_QUESTION_TO_EXISTING_BLOCK',
    REPOSITION_QUESTION = 'REPOSITION_QUESTION',
    CLEANUP_UNCONFIRMED_LOGIC = 'CLEANUP_UNCONFIRMED_LOGIC',
    RESTORE_STATE = 'RESTORE_STATE',
    SET_PAGING_MODE = 'SET_PAGING_MODE',
    REPLACE_SURVEY = 'REPLACE_SURVEY',
    SET_GLOBAL_AUTOADVANCE = 'SET_GLOBAL_AUTOADVANCE',
    CLEAR_LOGIC_VALIDATION_MESSAGE = 'CLEAR_LOGIC_VALIDATION_MESSAGE',
    ADD_BLOCK_FROM_AI = 'ADD_BLOCK_FROM_AI',
    UPDATE_TIMESTAMP = 'UPDATE_TIMESTAMP',
    ADD_SURVEY_FROM_LIBRARY = 'ADD_SURVEY_FROM_LIBRARY',
}

export interface Action {
    type: SurveyActionType;
    payload?: any;
}
